### ISSUE TITLE
Missing PAT values in generalstats.txt file

### ISSUE THREAD

**Issue by tbenavi1** [nhansen/q100bench#3]
Hello,

In the scaffolds, contigs, and aligned contig bases sections of the generalstats text file, we are missing the corresponding (PAT) values. For example, we have Scaffold NG50 (MAT) but not Scaffold NG50 (PAT). Or am I not understanding: Do MAT and PAT refer to the assembly or to the benchmark reference?

Also, in the log file, I get the following warnings:
```
Warning messages:
1: In par(pardefault) : graphical parameter "cin" cannot be set
2: In par(pardefault) : graphical parameter "cra" cannot be set
3: In par(pardefault) : graphical parameter "csi" cannot be set
4: In par(pardefault) : graphical parameter "cxy" cannot be set
5: In par(pardefault) : graphical parameter "din" cannot be set
6: In par(pardefault) : graphical parameter "page" cannot be set
```
I am not sure if these matter and are affecting the plots. Thanks!

**Comment by nhansen** [comment]
Hi Timothy. The R output was due to an error in an unnecessary line of code, so I've fixed it in the latest commit.

The question about "MAT" and "PAT" values for NG50, NGA50, etc. is a good one. When reporting these values, which measure coverage of a haploid genome, a decision has to be made about whether the length of the haploid genome is the longer maternal genome (of the benchmark) or the paternal. The "MAT" values for NG50, e.g., are the lengths of the shortest scaffolds/contigs which would need to be included to cover 50% of the maternal haplotype of the benchmark.

I've changed the code to report both MAT and PAT values, which are generally very similar. Do you think it's too much info? Maybe putting the values in a table would be better?

Thanks for your input!

**Comment by tbenavi1** [comment]
That's a good point about the values being similar. I am not sure whether it is too much info, but thanks for changing the code to report both.
